version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
